### ISSUE TITLE
简化Branch命名规范

### ISSUE THREAD

**Issue by fMeow** [PDFE/GUIDELINE#1]
Branch命名规范已经脱离github flow，而接近[gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)的标准了。

个人建议只有正在实现的新特性才需要新开branch。

**Comment by SukkaW** [comment]
branch 命名规范仅仅只是命名规范（As it is），你可以理解为在 GitLab Flow 的思想下进行 GitHub Flow。
因为对应到具体操作中，实际上绝大部分操作依然在几个主要分支中进行，只有较大的改动才会需要新建分支。
